name: Build
description: Build carl
inputs:
  build-env: 
    description: "Environment variables for the build"
    required: true
    default: ""

runs:
  using: "composite"
  steps:
    - name: Configure CMake
      shell: bash
      run: |
        echo "::group::Configure CMake"
        echo "Build directory: ${{github.workspace}}/build"
        echo "Build type: ${{env.BUILD_TYPE}}"
        echo ${{inputs.build-env.CC}} ${{inputs.build-env.CXX}}
        export CC=${{inputs.build-env.CC}} CXX=${{inputs.build-env.CXX}}
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        echo "::group::Configure CMake done"
    - name: Build carl
      shell: bash
      run: |
        echo "::group::Build carl"
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target all -j$(nproc)
        echo "::group::Build carl done"
