name: CI

on:
  push:
    branches: ["master"]
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build: 
    strategy:
      matrix:
        include: 
          #- name: ubuntu:gcc
          #  os: ubuntu-latest
          #  env: CC=gcc CXX=g++
#
          #- name: ubuntu:clang
          #  os: ubuntu-latest
          #  env: CC=clang CXX=clang++

          - name: macos:clang
            os: macos-latest
            env: CC=gcc CXX=g++ LDFLAGS="$LDFLAGS -undefined dynamic_lookup"
            bliss: OFF

    
    name: ${{matrix.name}}
    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        uses: ./.github/actions/install_dependencies

      - name: Compile
        uses: ./.github/actions/compile
        with:
          build-env: ${{matrix.env}}
          bliss: ${{matrix.bliss}}

      - name: Run Tests
        uses: ./.github/actions/run_tests